-- Сначала убираем зависимые таблицы, чтобы не мешали внешние ключи
DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS tickets;

CREATE TABLE departments (
                             id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name    TEXT NOT NULL
);

CREATE TABLE employees (
                           id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name       TEXT NOT NULL,
                           salary     INTEGER,
                           hire_date  DATE
);

CREATE TABLE teachers (
                          id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          full_name  VARCHAR(255) NOT NULL,
                          email      VARCHAR(255) NOT NULL
);

CREATE TABLE students (
                          id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          full_name   VARCHAR(255) NOT NULL,
                          enrolled_at DATE NOT NULL
);

CREATE TABLE courses (
                         id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name             VARCHAR(255) NOT NULL,
                         generation_hours INTEGER NOT NULL,
                         instructor_id    INTEGER NOT NULL,
                         max_students     INTEGER NOT NULL DEFAULT 20,
                         CONSTRAINT fk_courses_teacher FOREIGN KEY (instructor_id)
                             REFERENCES teachers (id)
);

CREATE TABLE enrollments (
                             student_id INTEGER NOT NULL,
                             course_id  INTEGER NOT NULL,
                             grade      NUMERIC(5,2),
                             PRIMARY KEY (student_id, course_id),
                             CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id)
                                 REFERENCES students (id),
                             CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id)
                                 REFERENCES courses (id)
);

CREATE TABLE tickets (
                         id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         concert_name  TEXT NOT NULL,
                         status        TEXT NOT NULL
);
